Repository ScreepsQuorum/screeps-quorum, pull requests merged in 2018-04, with the labels that each got.

#357 Revert "Sleep processes" - it has an error and has killed the public Quorum bot
  .gitignore
  src/qos/kernel.js
  src/qos/process.js
  src/qos/scheduler.js
Labels: Has Quorum, Passing

#358 Upgrade Notify script to match upstream project
  src/thirdparty/notify.js
Labels: Has Quorum, Passing

#361 Only use active spawns to spawn
  src/programs/spawns.js
Labels: Has Quorum, Passing

#362 add TS/lint capability
  package.json
Labels: Needs Votes, Passing

#360 Fixed sleeping upgrade
  .gitignore
  src/qos/kernel.js
  src/qos/process.js
  src/qos/scheduler.js
Labels: Needs Votes, Passing

#363 IVM heap statistics and garbage collection triggers
  src/qos/kernel.js
  src/thirdparty/sos_lib_cache.js
Labels: Has Quorum, Passing

#364 Fix README deploy example to match Gulpfile
  README.md
Labels: Has Quorum, Passing

#367 Fix error due to stats being undefined.
  src/qos/performance.js
Labels: Has Quorum, Passing

#368 Fix getHeapStatistics.
  src/qos/kernel.js
Labels: Has Quorum, Passing

#369 Improve room control level inheritance algorithm.
  src/extends/room/control.js
Labels: Has Quorum, Passing

#370 Lower Heap GC trigger and add percentage sign to log
  src/qos/kernel.js
Labels: Has Quorum, Passing

#372 Fix 'gateway' ramparts/walls.
  src/extends/room/construction.js
Labels: Has Quorum, Passing

#373 Add support for setting loglevel by group.
  src/qos/logger.js
Labels: Has Quorum, Passing

#375 Make the 'tick summary' logging slightly less verbose.
  src/qos/kernel.js
Labels: Has Quorum, Passing

#377 Update comments to be more accurate.
  src/extends/room/territory.js
  src/programs/empire/expand.js
Labels: gc-merged

#378 Fix npm publishing
  package.json
Labels: Has Quorum, Passing

#379 Fix some lab bugs (don't access properties of null/undefined).
  src/extends/room/alchemy.js
  src/roles/factotum.js
Labels: Has Quorum, Passing

#380 Create a passage for some weird layouts.
  src/extends/room/construction.js
Labels: Needs Votes, Passing

#383 Add some extra comments.
  src/programs/city/mine.js
Labels: Has Quorum, Passing

#381 Don't do reactions if there are no minerals.
  src/extends/room/alchemy.js
  src/roles/factotum.js
Labels: Has Quorum, Passing

#382 Have options to compile/deploy as TypeScript.
  gulpfile.js
  package.json
  tsconfig.json
Labels: Needs Votes, Passing

#384 Add some additional TypeScript 'typings' and options.
  package.json
  tsconfig.json
Labels: Needs Votes, Passing

#385 Add 'use strict' to all the files.
  src/extends/creep/actions.js
  src/extends/creep/overrides.js
  src/extends/mineral.js
  src/extends/room/control.js
  src/extends/room/landmarks.js
  src/lib/empire.js
  src/lib/events.js
  src/lib/genome.js
  src/lib/loader.js
  src/lib/map.js
  src/lib/notify.js
  src/programs/creep.js
  src/programs/empire/observers.js
  src/qos/performance.js
  src/thirdparty/creeptalk.js
  src/thirdparty/creeptalk_emoji.js
  src/thirdparty/distancetransform.js
  src/thirdparty/notify.js
  src/thirdparty/roomvisual.js
  src/thirdparty/sos_lib.js
  src/thirdparty/sos_lib_broadcaster.js
  src/thirdparty/sos_lib_charactors.js
  src/thirdparty/sos_lib_crypto.js
  src/thirdparty/sos_lib_monitor.js
  src/thirdparty/sos_lib_profiler.js
  src/thirdparty/sos_lib_segments.js
  src/thirdparty/sos_lib_serverid.js
  src/thirdparty/sos_lib_stormtracker.js
  src/thirdparty/sos_lib_termcom.js
  src/thirdparty/sos_lib_tickrate.js
  src/thirdparty/sos_lib_uuid.js
  src/thirdparty/sos_lib_vram.js
  src/version.js
  test/extends/roomposition/createBoundingBoxForRange.js
  test/helpers/screeps-globals.js
Labels: Has Quorum, Passing

#387 Add options to visualize layouts.
  src/programs/city.js
  src/programs/city/fortify.js
Labels: Has Quorum, Passing

#386 Add better error logging when something can't be constructed.
  src/extends/room/construction.js
  src/programs/city/construct.js
Labels: Needs Votes, Passing

#389 Increase the ratelimiting on errors to 1500 ticks
  src/qos/logger.js
Labels: Has Quorum, Passing

#390 Add some more logging to find link errors.
  src/extends/room/construction.js
Labels: Has Quorum, Passing

#391 Add more logging.
  src/extends/room/construction.js
Labels: Has Quorum, Passing

#392 source.getLink() now checks for links adjacent to miningPosition()
  src/extends/roomposition.js
  src/extends/source.js
  yarn.lock
Labels: Has Quorum, Passing

#393 Removed extra dependency bloat
  gulpfile.js
  package.json
  tsconfig.json
Labels: Failing, Has Quorum
